#collectors=[
#    "--path.procfs=/hostfs/proc",
#    "--path.sysfs=/hostfs/sys",
#    "--path.rootfs=/hostfs",
#    "--collector.arp",
#    "--collector.bcache",
#    "--collector.bonding",
#    "--collector.btrfs",
#    "--collector.conntrack",
#    "--collector.cpu",
#    "--collector.cpufreq",
#    "--collector.diskstats",
#    "--collector.dmi",
#    "--collector.edac",
#    "--collector.entropy",
#    "--collector.fibrechannel",
#    "--collector.filefd",
#    "--collector.filesystem",
#    "--collector.hwmon",
#    "--collector.infiniband",
#    "--collector.ipvs",
#    "--collector.loadavg",
#    "--collector.mdadm",
#    "--collector.meminfo",
#    "--collector.netclass",
#    "--collector.netdev",
#    "--collector.netstat",
#    "--collector.nfs",
#    "--collector.nfsd",
#    "--collector.nvme",
#    "--collector.os",
#    "--collector.powersupplyclass",
#    "--collector.pressure",
#    "--collector.rapl",
#    "--collector.schedstat",
#    "--collector.selinux",
#    "--collector.sockstat",
#    "--collector.softnet",
#    "--collector.stat",
#    "--collector.tapestats",
#    "--collector.textfile",
#    "--collector.thermal_zone",
#    "--collector.time",
#    "--collector.timex",
#    "--collector.udp_queues",
#    "--collector.uname",
#    "--collector.vmstat",
#    "--collector.xfs",
#    "--collector.zfs",
#    "--collector.processes"
#]
#[[relabel_configs]]
#source_labels = ["agent_hostname"]
#target_label = "instance"
#action = "replace"
collectors=[]
